
name: deploy-docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: set pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9


      - name: set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: set root config
        run: |
          sed -i 's|base: "/"|base: "/my-notes/"|g' src/.vuepress/config.ts
          sed -i 's|hostname: "https://lib.stazxr.cn/",|hostname: "https://www.stazxr.cn/my-notes/",|g' src/.vuepress/theme.ts

      - name: setup corepack
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: build docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: src/.vuepress/dist
